#!/usr/bin/env python3
"""Regenerates the flattened Wokwi copies of gateway.ino/node.ino and their
transitive core/transport/gateway header dependencies.

Why this exists: wokwi.com's browser IDE needs same-directory includes
(no "../core/pl_x.h"-style relative parents), so this script copies the
real source files in, rewriting only the include directives — never the
logic — so what runs in Wokwi is mechanically derived from the tested
source, not a hand-maintained fork that can drift out of sync.

gateway.ino additionally gets its WiFi/MQTT config constants swapped for
Wokwi-specific defaults (Wokwi-GUEST network, a public test broker,
since Wokwi's cloud simulator can't reach a broker on your LAN) — that
substitution lives HERE, not as a manual post-edit of the generated file,
specifically so re-running this script is safe and doesn't silently
discard it.

Run from the repo root: python3 wokwi/gateway-node/sync.py
Then re-check both copies still syntax-check clean (see this project's
README for the exact command).
"""

import re
import shutil
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = Path(__file__).resolve().parent

# Every core/transport/gateway header each sketch transitively includes,
# plus the sketch itself. Order doesn't matter — it's just a flat file set.
GATEWAY_FILES = [
    "core/pl_config.h",
    "core/pl_mac.h",
    "core/pl_registry.h",
    "core/pl_join.h",
    "core/pl_gateway_hsm.h",
    "core/pl_mqtt.h",
    "core/pl_spool.h",
    "core/pl_frame.h",
    "core/pl_fields.h",
    "core/pl_cmdtable.h",
    "core/pl_cmd_status.h",
    "core/pl_loss_tracker.h",
    "core/pl_dedupe.h",
    "core/pl_topics.h",
    "core/pl_ring.h",
    "transport/pl_transport.h",
    "transport/espnow/pl_espnow_transport.h",
    "gateway/pl_nvs_registry_storage.h",
    "gateway/pl_pubsubclient_mqtt.h",
    "gateway/gateway.ino",
]

NODE_FILES = [
    "core/pl_config.h",
    "core/pl_mac.h",
    "core/pl_registry.h",
    "core/pl_join.h",
    "core/pl_frame.h",
    "core/pl_fields.h",
    "core/pl_cmdtable.h",
    "core/pl_ring.h",
    "transport/pl_transport.h",
    "transport/espnow/pl_espnow_transport.h",
    "node/node.ino",
]

# Matches #include "(../)*maybe/some/path/file.h" — any relative-parent
# quoted include — and rewrites it to just #include "file.h". Angle-bracket
# includes (<WiFi.h>, <cstring>, ...) never match this and pass through
# untouched.
_INCLUDE_RE = re.compile(r'#include\s+"(?:\.\./)+(?:[\w-]+/)*([\w.]+)"')

_GENERATED_BANNER = (
    "// --- Wokwi copy, mechanically generated by wokwi/gateway-node/sync.py ---\n"
    "// Edits to includes or config constants made directly in this file will\n"
    "// be silently overwritten the next time sync.py runs. Change the real\n"
    "// source ({source}) or sync.py's substitution rules instead.\n"
    "// ---------------------------------------------------------------------\n\n"
)

# (pattern, replacement) pairs applied only to the flattened gateway.ino,
# after include-flattening. Keeps Wokwi-specific config reproducible
# instead of a manual edit that a re-run of this script would discard.
_GATEWAY_SUBSTITUTIONS = [
    (r'static const char\* kWifiSsid = ".*?";',
     'static const char* kWifiSsid = "Wokwi-GUEST";  // Wokwi\'s built-in open network'),
    (r'static const char\* kWifiPassword = ".*?";',
     'static const char* kWifiPassword = "";  // Wokwi-GUEST has no password'),
    (r'static const char\* kMqttHost = ".*?";',
     'static const char* kMqttHost = "test.mosquitto.org";  // public test broker — Wokwi\'s cloud simulator can\'t reach a LAN broker'),
]

# node.ino normally never calls WiFi.begin() (ESP-NOW doesn't need an AP
# connection — see node/README.md). This demo adds it anyway, purely to
# land the node on the same channel as the gateway, since neither board
# does real channel-scanning discovery (TRD.md §5.1) in this simplified
# example. Matched against the exact setup() text in node/node.ino.
_NODE_SUBSTITUTIONS = [
    (
        r'WiFi\.mode\(WIFI_STA\);\n\n  if \(esp_now_init\(\)',
        'WiFi.mode(WIFI_STA);\n'
        '  // Wokwi-only: join the same network as the gateway purely to land\n'
        '  // on its channel (see this project\'s README for why).\n'
        '  WiFi.begin("Wokwi-GUEST", "");\n'
        '  while (WiFi.status() != WL_CONNECTED) delay(200);\n\n'
        '  if (esp_now_init()',
    ),
]


def flatten_includes(text: str) -> str:
    return _INCLUDE_RE.sub(r'#include "\1"', text)


def sync(file_list, dest_dir: Path, *, ino_name: str, substitutions):
    dest_dir.mkdir(parents=True, exist_ok=True)
    for existing in dest_dir.glob("*"):
        if existing.name not in ("README.md",):
            existing.unlink()

    for rel_path in file_list:
        src = REPO_ROOT / rel_path
        text = src.read_text()
        text = flatten_includes(text)

        if rel_path.endswith(ino_name):
            for pattern, replacement in substitutions:
                new_text, n = re.subn(pattern, replacement, text)
                if n == 0:
                    raise RuntimeError(
                        f"substitution pattern did not match in {rel_path}: {pattern!r}"
                    )
                text = new_text
            text = _GENERATED_BANNER.format(source=rel_path) + text

        dest = dest_dir / Path(rel_path).name
        dest.write_text(text)
    print(f"wrote {len(file_list)} files to {dest_dir}")


if __name__ == "__main__":
    sync(GATEWAY_FILES, OUT_DIR / "gateway", ino_name="gateway.ino",
         substitutions=_GATEWAY_SUBSTITUTIONS)
    sync(NODE_FILES, OUT_DIR / "node", ino_name="node.ino",
         substitutions=_NODE_SUBSTITUTIONS)
